### ISSUE TITLE
Ember Upgrade for conduit-ui

### ISSUE THREAD

**Issue by jayjayjpg** [ConduitIO/conduit#1005]
## Description

In order to keep up with [security vulnerabilities more easily](https://github.com/meroxa/product/issues/749), we should upgrade Ember and it's related dependencies, such as `ember-cli`, `ember-data`, as well as version-dependent addons, e.g. `ember-auto-import`, `ember-changeset`, etc. to either

- the latest available minor version (`4.12` as of date). This way, we will be able to upgrade more quickly to Ember 5.x (which has already been released as of today)

- or the latest LTS version `4.8.x`. This way we can [still benefit from critical security patches within Ember until December 11, 2023](https://emberjs.com/releases/lts/)

## Blockers

This is a list of blockers that we encountered during the upgrade (tbd, once https://github.com/meroxa/platform-ui-v1/issues/881 had been worked through):

- [ ] Build error `@babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitution`

**Comment by simonl2002** [comment]
@jayjayjpg are you doing this work?

**Comment by simonl2002** [comment]
@jayjayjpg is focussed elsewhere and thus will not be tackling this ember upgrade work. For now we will push this work until the next version of Conduit after 0.7.0.

**Comment by jayjayjpg** [comment]
@simonl2002 I just timeboxed exploration on how much effort it would be to upgrade to at least 4.8 (the latest LTS version of Ember that still receives security patches until December 2023) as I mentioned briefly before and will close this ticket if the tests for this PR pass

I can create a follow-up ticket for the final upgrade to `4.12` which could be tackled in a future Conduit release (e.g. 0.7.0)

**Comment by jayjayjpg** [comment]
I created this follow-up ticket for the missing part of the upgrade: https://github.com/ConduitIO/conduit/issues/1012
