### ISSUE TITLE
Ember Upgrade to latest LTS (Q4 2023)

### ISSUE THREAD

**Issue by jayjayjpg** [ConduitIO/conduit#1012]
## Description

In order to keep up with security vulnerabilities more easily, we should upgrade Ember and it's related dependencies, such as `ember-cli`, `ember-data`, as well as version-dependent addons, e.g. `ember-auto-import`, `ember-changeset`, etc. once the [current LTS version that Conduit is on runs out of support](https://github.com/ConduitIO/conduit/pull/1011).

According to the current release calendar, LTS support will run out by **December 11, 2023**. This means, this ticket should be picked up the latest by Q4 2023 to guarantee that vulnerabilities of the UI project can be addressed in a timely manner.

For more information on the release cycle, see also https://emberjs.com/releases/lts/

### Steps to reproduce

.

### Version

.

**Comment by simonl2002** [comment]
This will be a stretch goal for 0.9.0

**Comment by lovromazgon** [comment]
UI will be deprecated soon.
