### ISSUE TITLE
Bug: Two connectors with the same ID cause panic

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1026]
### Bug description

If a pipeline configuration file declares two connectors with the same ID Conduit will panic when trying to run the pipeline.

### Steps to reproduce

1. Take the [`file-to-file.yml`](https://github.com/ConduitIO/conduit/blob/042149515d71b75d8e74a900c33dd8740f258d56/examples/pipelines/file-to-file.yml#L16) example pipeline and change the destination ID to `example.in`:

  ```diff
  ...
  -     - id: example.out
  +     - id: example.in
          type: destination
  ...
  ```

2. Run Conduit and pass in the file `./conduit --pipelines.path=./examples/pipelines/file-to-file.yml`
3. See panic:

```
2023-05-04T19:26:43+00:00 INF pipeline started component=pipeline.Service pipeline_id=file-to-file
panic: tried to run FaninNode without hooking the in channel up to another node

goroutine 88 [running]:
github.com/conduitio/conduit/pkg/pipeline/stream.(*FaninNode).Run(0x3cc4858?, {0x3ccaa50?, 0xc00053cc80?})
	/Users/lovro/dev/conduitio/conduit/pkg/pipeline/stream/fanin.go:39 +0x798
github.com/conduitio/conduit/pkg/pipeline.(*Service).runPipeline.func2()
	/Users/lovro/dev/conduitio/conduit/pkg/pipeline/lifecycle.go:566 +0x257
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0000bb180, 0x0?)
	/Users/lovro/go/1.20.0/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x36
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/Users/lovro/go/1.20.0/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xee
```

### Version

v0.7.0-nightly.20230504

**Comment by AdamHaffar** [comment]
what is the expected outcome of the fix? Should it be possible for conduit to accept 2 connectors with the same ID, or should it throw an error explaining that the connector IDs should not be the same?

**Comment by lovromazgon** [comment]
> throw an error explaining that the connector IDs should not be the same

☝️ this one
