### ISSUE TITLE
Connector: AWS Kinesis Destination

### ISSUE THREAD

**Issue by simonl2002** [ConduitIO/conduit#1079]
### Resource name

AWS Kinesis

### Resource link

https://aws.amazon.com/kinesis/

### Connector type

Destination

### Expected connector behavior

Connector will write events to AWS Kinesis stream.

**Comment by simonl2002** [comment]
Not scheduling now, potentially could prioritize for next release cycle.

**Comment by lovromazgon** [comment]
Let's release the connector and close this.

**Comment by alarbada** [comment]
Released [here](https://github.com/conduitio-labs/conduit-connector-kinesis/releases/tag/v0.1.0), so closing this.

**Comment by lovromazgon** [comment]
The release job failed 👎 https://github.com/conduitio-labs/conduit-connector-kinesis/actions/runs/11561875395/job/32181842833
