### ISSUE TITLE
Docker builds failing

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1107]
### Bug description

https://github.com/ConduitIO/conduit/actions/runs/5481712411/jobs/9986314164

Repoted by @maha-hajja 

### Steps to reproduce

Run release workflow

### Version

n/a

**Comment by hariso** [comment]
It appears to be caused by this: https://github.com/ConduitIO/conduit/commit/b1ec5a8e5f1ba899092a2e65ba601bbd4d8490e6

I've tried it out locally, on `golang:1.18` and `golang:1.20` and I cannot reproduce the issue on `1.18` (nor on `ubuntu:latest`) but can reproduce it on `1.20`.

**Comment by lovromazgon** [comment]
Hmm, how is this related to the error in the CI job though? 🤔 

```
#11 6.374 /bin/sh: 1: npm: not found
#11 ERROR: executor failed running [/bin/sh -c curl -sL https://deb.nodesource.com/setup_16.x | bash - &&    apt-get install -y nodejs &&    npm update &&    npm i -g yarn@1.22.17]: exit code: 127
```

**Comment by hariso** [comment]
@lovromazgon We're using NodeSource's Node.js distributions. For some reason, `npm` is correctly installed on Debian Bullseye (used in `golang:1.18`), but not on Debian Bookworm (used in `golang:1.20`). Debian Bookworm is pretty fresh so I guess the distribution needs a bit of polishing. They mention `Debian testing (Bookworm)` as supported on their list of supported OSes.

I've opened an issue for that: https://github.com/nodesource/distributions/issues/1601.
