### ISSUE TITLE
Add more example pipelines

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1118]
### Feature description

Originally suggested by @ahmeroxa:

Getting started with Conduit pipelines would be much easier if we had more examples of pipelines of different types (multiple sources, destinations, with and without processors, with and without DLQ, etc.)

Examples:

- [x] multiple sources
- [x] multiple destinations
- [x] source processor
- [ ] destination processors
- [x] js processor
- [x] usage of standalone connector
- [x] pipeline with a processor
- [x] pipeline with a dlq

**Comment by simonl2002** [comment]
We are going to split this into separate issues.
