### ISSUE TITLE
Bug: Extraneous plugin request via ember-data

### ISSUE THREAD

**Issue by jmar910** [ConduitIO/conduit#1133]
### Bug description

Ember data is making an extraneous request to a singular plugin resource, even though we have loaded them all up front. This is a pretty common ember-data bug, should be pretty straightforward to wrangle. 

### Steps to reproduce

https://meroxa.slack.com/archives/C01ERTL0MJR/p1689699088270599

### Version

v0.7.0

**Comment by simonl2002** [comment]
closing. we have not been able to repro
