### ISSUE TITLE
Better processors: better names 

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#1154]
Processor types are currently very hard to read. They are all in lowercase letters without spaces and normally end with "key" or "payload" depending on which field they manipulate (e.g. timestampconverterpayload).

We should make processor types easier to read and group together processors that do the same thing but work on different fields. The field could be chosen by a config option (see [ability to process any field](https://github.com/ConduitIO/conduit/issues/1155)).

**Comment by lovromazgon** [comment]
The new list of processors and their names is described in the [design document](https://github.com/ConduitIO/conduit/pull/1279), will be tackled in https://github.com/ConduitIO/conduit/issues/1290.
