### ISSUE TITLE
Better processors: processing any field

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#1155]
Currently built-in processors can only manipulate fields `Record.Key` and `Record.Payload.After`. We should change processors so they can be configured to work on any of the openCDC fields, maybe even multiple fields at the same time (e.g. copy payload data into metadata).

**Comment by lovromazgon** [comment]
The new list of processors and the way they will address fields is described in the [design document](https://github.com/ConduitIO/conduit/pull/1279), will be tackled in https://github.com/ConduitIO/conduit/issues/1290.
