### ISSUE TITLE
Better processors: Processor lifecycle

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#1157]
A processor is currently just a simple function that gets called for every record. There is no specific method called when initializing or closing a processor. To support more complex processors that need to open/close resources at the start/end we should introduce more methods.

**Comment by lovromazgon** [comment]
The proposed processor lifecycle is described in the [design document](https://github.com/ConduitIO/conduit/pull/1279), will be implemented as part of https://github.com/ConduitIO/conduit/issues/1285.
