### ISSUE TITLE
Feature: Allow processors to use the record templating

### ISSUE THREAD

**Issue by lyuboxa** [ConduitIO/conduit#1172]
### Feature description

Connectors support an output format based on templating, https://conduit.io/docs/connectors/output-formats#configuration-parameters

It will be nice if this was extended to processors where the user can define what parts of the record are fed to the processor.
The [httprequest](https://github.com/ConduitIO/conduit/blob/main/pkg/processor/procbuiltin/httprequest.go#L92) processor is an example where it will only forward the value of `After` section of the `Payload` record.

**Comment by simonl2002** [comment]
This isn't the highest priority but we may consider adding this after initial better processor work.

**Comment by simonl2002** [comment]
This was done in the general better processor work #1378
