### ISSUE TITLE
The backend web UI management does not have a password, and any user can operate it, which is not secure

### ISSUE THREAD

**Issue by mmm8955405** [ConduitIO/conduit#1206]
### Feature description

Add backend administrator password

**Comment by lovromazgon** [comment]
Hi @mmm8955405! This seems more like a feature request than a bug, so I marked it as such. The current UI is not meant to be publicly hosted, although we have discussed adding user management to Conduit, but there were more essential features we had to focus on.

In the meantime, while this is not implemented in Conduit, I propose you look into adding a proxy server that sets up authentication in front of Conduit (e.g. nginx).

**Comment by devarispbrown** [comment]
@mmm8955405 can you talk more about what you're trying to do that you would need a password for the UI?

**Comment by mmm8955405** [comment]
> Hi @mmm8955405! This seems more like a feature request than a bug, so I marked it as such. The current UI is not meant to be publicly hosted, although we have discussed adding user management to Conduit, but there were more essential features we had to focus on.
> 
> In the meantime, while this is not implemented in Conduit, I propose you look into adding a proxy server that sets up authentication in front of Conduit (e.g. nginx).

Okay, but I think we need the password for the UI

**Comment by mmm8955405** [comment]
> @mmm8955405 can you talk more about what you're trying to do that you would need a password for the UI?

Yes, a password for the UI should be required. Even though there is still a lot to be done at the moment

**Comment by mmm8955405** [comment]
There may still be some issues at present. In the latest Docker image:
[https://github.com/ConduitIO/conduit/issues/1207](https://github.com/ConduitIO/conduit/issues/1207)

**Comment by lovromazgon** [comment]
UI will be deprecated soon, see https://github.com/ConduitIO/conduit/issues/1911.
