### ISSUE TITLE
Bug: withValues failed to assign key 6 into []*uint8

### ISSUE THREAD

**Issue by dylanlott** [ConduitIO/conduit#121]
### Bug description

`withValues failed to assign key: cannot assign 6 into *[]uint8` is showing up in the logs when trying to parse back a value from Postgres. Investigate why and and what value caused this to see if it's our fault or user error.

### Steps to reproduce

1. Start conduit 
2. Start a Postgres plugin with the `test/` docker-compose postgres setup running.
3. Insert a record into the postgres table with primary key of an integer

### Version

v0.1.0

**Comment by samirketema** [comment]
Just chiming in with additional context - I ran into this issue. If it helps, it specifically showed when I also had a destination pg connector.
