### ISSUE TITLE
Redpanda Source/Destination

### ISSUE THREAD

**Issue by simonl2002** [ConduitIO/conduit#1372]

**Comment by lovromazgon** [comment]
@simonl2002 we already have the kafka connector that is compatible with redpanda, we even run [tests against redpanda](https://github.com/ConduitIO/conduit-connector-kafka/blob/edd92912c5682a7f20c8848eaefc25ec0fbf9b71/.github/workflows/test.yml#L22). Is there a reason to create a separate connector?

**Comment by simonl2002** [comment]
@lovromazgon this was a request, but let me check in on that.
