### ISSUE TITLE
Connector: Redshift Destination

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#14]
We need a Redshift destination connector.

**Comment by hariso** [comment]
The connector is being developed here: https://github.com/conduitio-labs/conduit-connector-redshift It's mostly done and currently it's in [this branch](https://github.com/conduitio-labs/conduit-connector-redshift/tree/destination). It's undergoing some testing before a PR is opened.

**Comment by simonl2002** [comment]
Redshift connector exists: https://github.com/conduitio-labs/conduit-connector-redshift
