### ISSUE TITLE
MC: Postgres Source - Read from multiple tables

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1473]
- Enable reading from multiple tables in both modes, replacing the existing `postgres.table` field with `opencdc.collection`.
  - CDC https://github.com/ConduitIO/conduit-connector-postgres/pull/129
  - longpolling
- Implement wildcard functionality to listen to all tables (`*`).

**Comment by raulb** [comment]
> * Enable reading from multiple tables in both modes (CDC, longpoll), replacing the existing `postgres.table` field with `opencdc.collection`.
> * Implement wildcard functionality to listen to all tables (`*`).

@lovromazgon when it comes to listening to all columns, we decided to use the pattern of absence:

> If no column names are provided in the config, then the connector will assume that all columns in the table should be returned.

Maybe we should do the same for columns, providing a wildcard so the design is consistent. This would be my preference. What do you think?

**Comment by lovromazgon** [comment]
That readme is outdated 🙈 The `columns` configuration parameter was [removed completely](https://github.com/ConduitIO/conduit-connector-postgres/pull/113/files#diff-2f3155aea603bde2c43d7e87f9fd14baf61f282ae3df1873fd70dd6456abc472L46), we always read all columns right now. The user can still filter out columns with a processor.

**Comment by raulb** [comment]
@lovromazgon opened a PR to update it https://github.com/ConduitIO/conduit-connector-postgres/pull/130

**Comment by raulb** [comment]
This shipped https://github.com/ConduitIO/conduit-connector-postgres/releases/tag/v0.7.0
