### ISSUE TITLE
Conduit 0.10 Blog Post

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1503]

**Comment by raulb** [comment]
Draft lives in Notion: https://www.notion.so/meroxa/Announcing-Conduit-0-10-0-57d41c3888fd49ed9b2a125beb9f0d4a?pvs=4

**Comment by lovromazgon** [comment]
https://meroxa.com/blog/conduit-0.10-comes-with-multiple-collections-support/
