### ISSUE TITLE
Add scarf tracking

### ISSUE THREAD

**Issue by simonl2002** [ConduitIO/conduit#1504]
### Feature description

To aid with visibility it would be great to add scarf info into the following places:

- Adding the new Docker endpoint to your GitHub README: https://github.com/ConduitIO/conduit/tree/main?tab=readme-ov-file#docker
- Replacing the Docker endpoint in your GitHub Releases with the Scarf endpoint: https://github.com/ConduitIO/conduit/releases
- Creating a Scarf file package to track your binaries, and providing links to those packages in your GitHub release notes (see how Telepresence has done this here: https://github.com/telepresenceio/telepresence/releases/ and how Smallstep has done this here: https://github.com/smallstep/certificates/releases)

**Comment by raulb** [comment]
@maha-hajja approved and merged your pull-requests so we could start collecting data already. Thank yo for making this change!

**Comment by maha-hajja** [comment]
the scarf package link for conduit release `conduit.gateway.scarf.sh/conduit/download/v{version}/conduit_{version}_{os}_{arch}.{ext}`

**Comment by simonl2002** [comment]
Closing this, initial goals met. @maha-hajja will create new tickets for automation and additional pixels
