### ISSUE TITLE
UI end to end tests that rely on a real conduit instance

### ISSUE THREAD

**Issue by dylanlott** [ConduitIO/conduit#154]
### Feature description

The UI should have end to end tests that interact with a real Conduit server.

**Comment by neovintage** [comment]
@dylanlott Did something not get tested appropriately because it wasn't a real Conduit server? Or is this a nice to have?

**Comment by dylanlott** [comment]
This is a nice to have that came out of discussion around #42. #42 is specific about end to end tests for only conduit, but eventually we want end to end tests that drive conduit UI around with a real conduit server. We talked yesterday and @jmar910 has more input here, since this ticket will fall into their realm.

**Comment by hariso** [comment]
Closing this issue since we're deprecating the UI.
