### ISSUE TITLE
Schema support

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1560]
### Feature description

Adds support for schemas in Conduit. The work is split as in the lists below. It would be good if we start with #1561 and the conduit-commons issues (minus schema auto-generation) so we can parallelize the rest of the work.

**Conduit**

- [x] #1561
- [x] #1562
- [x] #1563
- [x] #1653
- [x] #1660
- [x] #1707
- [x] #1719

**conduit-commons**

- [x] https://github.com/ConduitIO/conduit-commons/issues/50
- [x] https://github.com/ConduitIO/conduit-commons/issues/52
- [x] https://github.com/ConduitIO/conduit-commons/issues/53
- [x] https://github.com/ConduitIO/conduit-commons/issues/51

**Connector SDK**

- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/132
- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/137
- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/138
- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/158

**Processor SDK**

- [x] https://github.com/ConduitIO/conduit-processor-sdk/issues/45

**Schema registry**

- [x] https://github.com/ConduitIO/conduit-schema-registry/issues/3

**Comment by lovromazgon** [comment]
A lot, if not all of the code, needed for auto-generating Avro schemas can be found [here](https://github.com/ConduitIO/conduit/blob/main/pkg/plugin/processor/builtin/impl/avro/schemaregistry/avro/extractor.go).

The utilities mentioned in both SDKs can be placed in conduit-commons, so we can re-use it.

**Comment by lovromazgon** [comment]
Shipped in https://github.com/ConduitIO/conduit/releases/tag/v0.11.0
