### ISSUE TITLE
[Schemas] In-memory schema service

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1561]
Part of https://github.com/ConduitIO/conduit/issues/1560.

We need to implement a service that exposes methods to fetch and register schemas. The service will be used for other internal, connector-related, methods.  "Connector utility service" is just a working name, we can change to whatever we agree might be better.

It also needs to run on a randomly generated port (in the future this port might be made configurable). The port should be exposed through an environment variable so that connectors can use it.

In this issue, we can have an in-memory implementation, so that the Connector SDK work can be unblocked.

**Note**: We should keep in mind that connectors and processors communicate with Conduit differently.

**Comment by lovromazgon** [comment]
https://github.com/ConduitIO/conduit/blob/main/pkg/plugin/processor/builtin/impl/avro/schemaregistry/fake.go

**Comment by hariso** [comment]
Closed with #1605 and https://github.com/ConduitIO/conduit-connector-protocol/pull/88.
