### ISSUE TITLE
[Schemas] Limit schema service usage to connectors

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1563]
Part of #1560.

The schema service is currently intended to be used by connectors only. To limit the usage of the service to connectors only we should generate a magic cookie that a connector will use to identify itself (can be saved in an environment variable).

We should also run the schema service on a "random" port.

Pull requests:
- https://github.com/ConduitIO/conduit-connector-protocol/pull/112
- https://github.com/ConduitIO/conduit-connector-sdk/pull/150
- https://github.com/ConduitIO/conduit/pull/1701

**Comment by raulb** [comment]
@hariso @lovromazgon apologies I couldn't bring this one home before I took some time off.

What I was planning on doing was adding to `pkg/plugin/schema_cookie.go` on conduit the following:

```go
package plugin

import (
	"fmt"
	"math/rand"
	"os"
	"strings"
	"time"

	"github.com/conduitio/conduit/pkg/plugin/connector"
)

const charset = "abcdefghijklmnopqrstuvwxyz" +
	"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

func randomString(length int) string {
	rand.New(rand.NewSource(time.Now().UnixNano()))
	sb := strings.Builder{}
	sb.Grow(length)
	for i := 0; i < length; i++ {
		sb.WriteByte(charset[rand.Intn(len(charset))])
	}
	return sb.String()
}

// GetSchemaCookieValue receives the name of the plugin and the version, and registers into the provided context a cookie that will be used later on to validate if this plugin is registered.
// This cookie will be stored in an environment variable
func GetSchemaCookieValue(pluginName, pluginVersion string) (connector.SchemaCookie, error) {
	name := strings.ToUpper(fmt.Sprintf("%s_%s", pluginName, pluginVersion))
	value := randomString(32)

	if err := registerCookie; err != nil {
		return connector.SchemaCookie{}, err
	}

	return connector.SchemaCookie{
		Name:  name,
		Value: value,
	}, nil

}

func registerCookie(cookie connector.SchemaCookie) error {
	return os.Setenv(cookie.Name, cookie.Value)
}
```

**Comment by hariso** [comment]
@raulb No problems at all, you already did a lot and didn't leave us much work at all!
