### ISSUE TITLE
Info endpoint not showing version of downloaded Conduit

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#162]
### Bug description

When running the Conduit binary found in one of the GitHub releases, and then inspecting the info endpoint `http://localhost:8080/info` shows the version as an empty string. The Docker image correctly shows the version in this endpoint.

### Steps to reproduce

1. Download any release from the GH releases
2. Unzip, run Conduit
3. Open http://localhost:8080/info in browser.

**Expected**
```json
{
  "version": "v0.1.1",
  "os": "linux",
  "arch": "amd64"
}
```

**Actual**
```json
{
  "version": "",
  "os": "linux",
  "arch": "amd64"
}
```

### Version

v0.1.1 any OS/arch

**Comment by lovromazgon** [comment]
Note to self (or the person implementing) - need to add this option to `.goreleaser.yml`:
```
    ldflags:
      - "-s -w -X github.com/conduitio/conduit/pkg/conduit.version={{ .Tag }}"
```

Sidenote: we should also add a `date` field and bind `{{ .Date }}` to it, this way we can display when the binary was built, it would give the user a quick idea of how old the version they are using is.

Useful resources:
- [Name Templates](https://goreleaser.com/customization/templates/) in goreleaser
- [`builds` section](https://goreleaser.com/customization/build/) (see `ldflags` option)
