### ISSUE TITLE
Bug: field.set processor can not set a new field at the .Payload level

### ISSUE THREAD

**Issue by tsinghgill** [ConduitIO/conduit#1668]
### Bug description

We are trying to set the field **field: ".Payload.Data"** however it throws an error. According to the [docs](https://conduit.io/docs/processors/builtin/field.set/) this processor will create the field if it does not exist. The below configuration does not work.

`    processors:
      - id: add-data-field
        plugin: "field.set"
        settings:
          field: ".Payload.Data"
          value: "{{.Payload.After}}"`
          
We tested this configuration locally, where we set **field: ".Payload.After.Data"** and this works:

`    processors:
      - id: add-data-field
        plugin: "field.set"
        settings:
          field: ".Payload.After.Data"
          value: "{{.Payload.After}}"`
          

### Steps to reproduce

Set this configuration in your pipeline, essentially cloning the **.Payload.After** to **.Payload.Data**:

`    processors:
      - id: add-data-field
        plugin: "field.set"
        settings:
          field: ".Payload.Data"
          value: "{{.Payload.After}}"`
          

### Version

0.10.1 darwin/arm64

**Comment by lovromazgon** [comment]
We can't do that, the record will always have the structure of an [opencdc record](https://conduit.io/docs/features/opencdc-record). We can't add an arbitrary field anywhere in the record, that only applies to `.Payload.After`, `.Payload.Before` and `.Key`, as only those fields can contain structured data.

In other words, the fields in an OpenCDC record are always the same, can't be removed, renamed or new fields attached. You should look at it as the envelope that carries the actual data.

What you might be able to do is use the template record formatter, which lets you use a [Go template](https://pkg.go.dev/text/template) and be very flexible with what is actually written into the destination: https://conduit.io/docs/connectors/output-formats/
