### ISSUE TITLE
Bug: pipeline.index J.randomUUID is not a function

### ISSUE THREAD

**Issue by MichalisDBA** [ConduitIO/conduit#1669]
### Bug description

Hello. I have the same problem as mentioned here https://github.com/ConduitIO/conduit/issues/1207. 

I am running AlmaLinux 9.4. I downloaded the latest .rpm file `conduit_0.10.2_Linux_x86_64.rpm` and install it with `rpm -ivh conduit_0.10.2_Linux_x86_64.rpm`

i started the conduit by simply run `conduit`.

The server started and open the webpage. Tried to press `Create pipeline` but it does not work. In console there are error messages

![image](https://github.com/ConduitIO/conduit/assets/68512501/f10a6f6b-01c9-4add-b51c-b94fc7e0ea87)

Tried with both browsers, Firefox and Edge. Same problem

### Steps to reproduce

OS: AlmaLinux 9.4
Download:
`wget https://conduit.gateway.scarf.sh/conduit/download/v0.10.2/conduit_0.10.2_Linux_x86_64.rpm`
Install:
`rpm -ivh conduit_0.10.2_Linux_x86_64.rpm`
Run:
`conduit`
Open browser and try to press `Create pipeline` button.
Nothing works and throws an error in console:
`pipeline.index J.randomUUID is not a function`

### Version

v0.10.2 linux/amd64

**Comment by hariso** [comment]
@MichalisDBA I've just tried with AlmaLinux 9.4 in a Docker container, and it works. It could be very well an issue related to the version of the browser you're running (mine is Firefox 126.0.1 and Vivaldi 6.7).

**Comment by MichalisDBA** [comment]
Hi @hariso. Try it without docker. Just install the rpm package with the binary files. I do not use docker. Also tried it with Firefox and Edge. Same problem.

**Comment by hariso** [comment]
I installed Conduit using a Debian package too, and it works... Do you mind running Conduit with `docker run -p 8080:8080 ghcr.io/conduitio/conduit` and trying it out that way? Personally, I doubt the OS/installation method matters much.

**Comment by MichalisDBA** [comment]
I have RHEL based Linux systems. Almalinux is one of them. The thing is conduit has binary files that you can run but they are not working on RHEL Clone systems as it seems. Docker image maybe is based on debian that's why on debian and on docker it runs.

They thing is they need to fix their binaries for other systems or else pull them from the release page.

**Comment by MichalisDBA** [comment]
Also i tried and build the binary file from source. Same error in console from the build binary file.

**Comment by hariso** [comment]
I'm from the Conduit team, I'll try to help as much as possible. What version of Go and yarn were you using when you built Conduit?

I ran [Alma Linux 9.4 in a Docker container](https://hub.docker.com/layers/library/almalinux/9.4/images/sha256-9174caa563cb35879c4e696798b63dc17d518fe74a9cd347c64b3ee687dcd2f2?context=explore) (and I don't expect it to have significant differences versus a "normal" Alma Linux installation).

Then I installed Conduit following the steps you provided (wget, rpm -ivh), and it worked.

**Comment by MichalisDBA** [comment]
I run Alma Linux 9.4 in a VM not as a docker container, minimal installation. You have to try it in a VirtualBox or some else virtualization software. Maybe your situation works because alma linux docker container shares some things with the host machine you run it, for example debian.

I test in on a clean Alma Linux 9.4 installation in VirtualBox. Latest version of GO 1.22 and YARN

**Comment by MichalisDBA** [comment]
Clean installation

![image](https://github.com/ConduitIO/conduit/assets/68512501/131bb2ff-6b99-498f-8a27-83fbdc97ac08)

Run ./conduit

![image](https://github.com/ConduitIO/conduit/assets/68512501/133cef43-4fcd-40aa-9967-9ac294bf31ca)

Try to Create Pipeline

![image](https://github.com/ConduitIO/conduit/assets/68512501/772e29b7-3f4a-4c03-ad0f-83546ce9bfe3)

**Comment by hariso** [comment]
Hmm, I don't think a Docker container is supposed to share anything with the host (unless you explicitly tell it, which we don't).

How about NodeJS, which version of it are you using?

**Comment by hariso** [comment]
Also, when you get to it, can you please share the output of `yum list installed`?

**Comment by MichalisDBA** [comment]
I can give you access to a fresh VM in Hetzner running AlmaLinux 9.4 to try for youself. Is there a contact info to send you the SSH login?

**Comment by raulb** [comment]
Hi @MichalisDBA! Sorry you ran into this issue 😔. Until we find the culprit of this UI bug, could we maybe help you get started with your pipeline using a [pipeline configuration file](https://conduit.io/docs/pipeline-configuration-files/getting-started) instead?

Steps involved would require not using the UI, so I hope you are comfortable there.

**Comment by hariso** [comment]
Closing this issue since we're deprecating the UI.
