### ISSUE TITLE
Feature: conduit_connector_records metric

### ISSUE THREAD

**Issue by simonl2002** [ConduitIO/conduit#1698]
# Feature description

Conduit Currently has a `conduit_connector_bytes` metric but it would be helpful to have a similar `conduit_connector_records` metrics that captures the number of records the connector processes. 

So to capture all the info:
```
name: conduit_connector_records
type: histogram
description: Number of records a connector processed by pipeline name, plugin and type (source, destination).
```

**Comment by lovromazgon** [comment]
`conduit_connector_bytes` is a Prometheus histogram which is a collection of metrics. The count can be fetched using `conduit_connector_bytes_count`. We need to update the docs so this is clearer to the end-user.
