### ISSUE TITLE
CI: Authenticate Buf actions

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1710]
Email from Buf:

> As of **August 1, 2024**, Buf will begin limiting remote plugin requests from unauthenticated users on [buf.build](https://buf.build/). If you send more than 10 unauthenticated requests per hour using [remote plugins](https://buf.build/docs/bsr/remote-plugins/overview), you’ll begin to see rate limit errors.
> 
> We’ll start by failing a small percentage of unauthenticated requests, increasing over time until 100% of unauthenticated requests are blocked. To prevent service interruptions, please update your CI jobs and local usages of the Buf CLI to authenticate with the Buf Schema Registry (BSR) before making these requests.

We use remote plugins in our config and need to authenticate in the action that generates the buf code ([`validate-generated-files.yml`](https://github.com/ConduitIO/conduit/blob/main/.github/workflows/validate-generated-files.yml)). See [Buf docs](https://buf.build/docs/bsr/authentication) on how to achieve that.

We need to do the same in all repos that use buf (at least conduit-commons, conduit-connector-protocol and conduit-processor-sdk, investigate if there are any others).

Repositories on https://buf.build/conduitio:

- [x] conduit https://github.com/ConduitIO/conduit/pull/1770
- [ ] conduit-commons https://github.com/ConduitIO/conduit-commons/pull/93
- [x] conduit-connector-protocol https://github.com/ConduitIO/conduit-connector-protocol/pull/124
- [x] conduit-processor-sdk https://github.com/ConduitIO/conduit-processor-sdk/pull/72

**Comment by hariso** [comment]
I'm reopening the issue until I copy the actions from Conduit into other repos.

**Comment by raulb** [comment]
Closing now!
