### ISSUE TITLE
Document best practices when building connectors

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1757]
### Feature description

With the many connectors we've written over time, I think we can share some good advice when it comes to writing connectors (setup, snapshots vs CDC in sources, consistent snapshots, different CDC methods, handling keys, positions, etc.).

**Comment by raulb** [comment]
We should make sure we also include a way to test them. See discussion [here](https://github.com/ConduitIO/conduit/discussions/1724#discussioncomment-10178484).
