### ISSUE TITLE
Terraform Provider

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#18]
Because conduit is software that is meant to be run as a service, developers will want ways to easily repeat their setup process. Conduit needs to be able to be set up via terraform.

**Comment by simonl2002** [comment]
@neovintage Do we still see a need for this? I'd say terraform would more assist with setting up the infra and deploying whatever container conduit was built into. Because it is a single binary there's not much do really do.

**Comment by simonl2002** [comment]
Closing due to lack of demand.
