### ISSUE TITLE
S3 SDK migration bug: not all records written to destination

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#190]
### Bug description

* for S3-S3 pipeline: only one file gets transferred to the S3 destination bucket.
* for S3-file pipeline: all records are transferred successfully to the file.

So S3 destination is mostly the problem.

### Steps to reproduce

* create a pipeline with S3 source and destination from the branch [maha/conduit-plugin-7-S3](https://github.com/ConduitIO/conduit/tree/maha/conduit-plugin-7-S3)
* run the pipeline and notice only one file is transferred to the destination

### Version

sdkMigration

**Comment by lovromazgon** [comment]
Closing as this is not a bug that exists on main, it was only on a feature branch and it was fixed as well.
