### ISSUE TITLE
Feature: Support .env files for env vars

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#1905]
### Feature description

for env vars used in pipeline config file, support providing the `.env` file to get the env vars from

**Comment by timwehrle** [comment]
I can look into this.

**Comment by lovromazgon** [comment]
This can already be done with tools like `dotenv`. What we need to do though is document the environment variables thoroughly (tracked in this issue: https://github.com/ConduitIO/conduit-site/issues/150).
