### ISSUE TITLE
Nightly builds: Mark as pre-release

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#197]
### Feature description

Nightly releases should be marked as pre-releases so that the "latest" release is still the last release triggered by a version tag.

**Comment by hariso** [comment]
I've asked about this on GoReleaser's Discord server: https://discord.com/channels/890434333251362866/892235027998466099/940906453324144640

**Comment by lovromazgon** [comment]
Looks like a simple fix then!
