### ISSUE TITLE
bug: dev and deprecated flags shown by when running `conduit help`

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#1971]
### Feature description

The --dev flags (used for profiling) should be hidden when `conduit help` is run. This is how we had before v0.12.2 when we unintentionally made them visible by default as part of some other CLI changes.

**Comment by raulb** [comment]
@hariso looks like an easy fix. Maybe we could pull this one in.

**Comment by hariso** [comment]
@raulb Agreed!

**Comment by raulb** [comment]
Looks like the deprecated flag `--pipelines.exit-on-error` is also being shown. Looks like there was a regression somewhere.

**Comment by hariso** [comment]
> Looks like the deprecated flag `--pipelines.exit-on-error` is also being shown. Looks like there was a regression somewhere.

It's probably related to the changes I introduced when I was working on `conduit init`: https://github.com/ConduitIO/conduit/blob/main/cmd/cli/cli.go#L62

**Comment by raulb** [comment]
@hariso ready for review https://github.com/ConduitIO/conduit/pull/1974.
