### ISSUE TITLE
Feature: Default `make` should work

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#206]
### Feature description

If a developer wants to build from source. The instructions should be as simple as running `make` from the command line.

**Comment by hariso** [comment]
@neovintage possibly same as https://github.com/ConduitIO/conduit/pull/140?

**Comment by neovintage** [comment]
@hariso Ha! yeah. I tried to do this on `main` and it didn't work for me. I'm getting build errors.

**Comment by neovintage** [comment]
Closing. The issue was my version of go. I was on 1.16 and I needed 1.17. This situation will be fixed by #151.
