### ISSUE TITLE
Plugin: Get Record.ReadAt from plugin

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#223]
### Feature description

Right now Conduit populates the field `ReadAt` in a record. Since the source connector plugin is now in charge of reading records and streaming them to Conduit asynchronously it would make more sense for the plugin to populate that field when it actually reads the record, instead of for Conduit when it receives the record.

Think about if it makes sense to still have the information about when Conduit received the record from the plugin and store it in the record.

**Comment by uchennakevinm1** [comment]
This is a part of the OpenCDC issue.

**Comment by hariso** [comment]
This information is used in performance benchmarks, to measure how much time do records spend in Conduit itself. If really needed, maybe we can have two fields: one for when the record was read, and one for when it was received? Do we use the ReadAt for something other than the benchmarks?

**Comment by lovromazgon** [comment]
This field will be moved into metadata in the OpenCDC record. As part of the OpenCDC definition we have standard metadata fields meant to store when the record was created on the 3rd party system and when it was read by the connector (see [this](https://github.com/ConduitIO/conduit-connector-protocol/pull/8/files#diff-b13e57d4d4b83105028a1dbc6ec8eb016cc569c0dc9e5fe8c80d00591803a358R8-R13)). It depends on the connector if those fields will be populated, though at least the "read at" field is populated if the developer uses the SDK utility method for creating a record (see [this](https://github.com/ConduitIO/conduit-connector-sdk/pull/31/files#diff-a4d006ab5233eeae48e5dc55c19a888b1a1ab4edcda548ba466e8a88909ed063R312)).

We don't plan to use this information for anything specific, it's basically just metadata.
