### ISSUE TITLE
Bug: Standalone connector Configure/Teardown panic not caught

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#224]
### Bug description

When a connector is created Conduit runs the connector plugin and tries to configure it with the supplied configuration. After that it calls `Teardown` and stops the plugin. If the plugin panics in `Teardown` and stops with an error, that error is not propagated to the caller and the connector is created successfully. The expected behavior is for the connector creation to be aborted and the error to bubble up to the caller.

### Steps to reproduce

1. Have a connector plugin that panics when `Teardown` is called.
2. Create a pipeline
3. Create a connector using plugin mentioned in point 1 in standalone mode.
4. See error and panic in log, but connector was successfully created

### Version

lovro/conduit-plugin (branch not merged yet)

**Comment by uchennakevinm1** [comment]
@lovromazgon Can you be more specific in the instructions to reproduce

**Comment by lovromazgon** [comment]
I meant the teardown function [here](https://github.com/ConduitIO/conduit/pull/513/files#diff-057275efdc3127c983d5553ee05174380268e80d794139f7ff66e8ce6ab0d4c4L115) and [here](https://github.com/ConduitIO/conduit/pull/513/files#diff-d9c7919dd9a14d89eecc7ce21033ed032fbe8cb9e43efcd1df32605c466f3740L115). It was an easy fix so I just created a [PR](https://github.com/ConduitIO/conduit/pull/513) for it, I was already thinking about creating a utility function for this for a long time because we will need it in [almost](https://github.com/ConduitIO/conduit/blob/8c534b14679f2f1bb5a726e9fb7ca7249ee4f3bf/pkg/pipeline/stream/destination.go#L75-L80) [all](https://github.com/ConduitIO/conduit/blob/8c534b14679f2f1bb5a726e9fb7ca7249ee4f3bf/pkg/pipeline/stream/destination_acker.go#L70-L75) [nodes](https://github.com/ConduitIO/conduit/blob/8c534b14679f2f1bb5a726e9fb7ca7249ee4f3bf/pkg/pipeline/stream/source.go#L69-L75). I didn't change those nodes though because the PRs I have open will change them and it would create a conflict.
