### ISSUE TITLE
Clustered Conduit

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#24]
The problem to solve is High Availability. Should one node go down, another will need to take it's place. The goal is not disaster recovery. We will need to develop a separate solution for that.

**Comment by hariso** [comment]
Random thought about this: we should think about how to work with standalone plugins when Conduit is clustered. The plugin executables need to be found on all instances (if we want to make it possible that any Conduit instance in a cluster can work on any pipeline).

**Comment by simonl2002** [comment]
I think this is still pretty far out in the future @neovintage? Especially if there's a conduit Kubernetes operator which can help with orchestration.

**Comment by simonl2002** [comment]
Closing, the Conduit Kubernetes operator work will address running Conduit in a distributed manner.
