### ISSUE TITLE
Feature: Credential injection via command line

### ISSUE THREAD

**Issue by dannob** [ConduitIO/conduit#251]
### Feature description

I have a small request regarding credential management for conduit.  I would like to inject my AWS keys from the command line (environment vars) for use in accessing AWS resources like S3.  Thanks!

**Comment by hariso** [comment]
@dannob Thanks for submitting this feature request! May I ask to clarify a bit more, what kind of AWS resources would you like to access from Conduit, i.e. what are your use cases? 

We do have an S3 plugin, which allows you to stream data from S3 or into S3, and that plugin can be easily configured.

**Comment by lovromazgon** [comment]
We plan to address this issue in #32, which will add a way to define a pipeline in a configuration file that Conduit loads at startup. It will be possible to inject environment values in that file, I think this should cover your use case.

I'm closing the issue now as this will be addressed in another issue, let us know if you had something different in mind.
