### ISSUE TITLE
Bug: No unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#282]
### Bug description

The Postgres destination fails if the target table in Postgres does not contain a primary key. This is the error it throws:

```
ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10)
```

A possible solution is to not add the `ON CONFLICT` part of the query if there is no primary key (in that case no conflict can occur anyway).

Related: https://github.com/ConduitIO/conduit/pull/279#discussion_r819755458

### Steps to reproduce

1. Create two tables in Postgres with the same structure, one with a primary key, another without.
2. Set up a pipeline reading from the one with a primary key and writing into the table without a primary key.
3. See error.

### Version

v0.1.0

**Comment by dylanlott** [comment]
Related question: Do we want to require a primary key, or if one is not set, alter the table to our own sane default?

**Comment by lovromazgon** [comment]
We should check if there is a primary key on the table on `Open` and throw an error if it doesn't. Also document this behavior in the readme.

**Comment by dylanlott** [comment]
Fixed by https://github.com/ConduitIO/conduit-connector-postgres/pull/16
