### ISSUE TITLE
Feature: Kafka connector should support SASL

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#283]
### Feature description

SASL is widely used and a recommended mechanism for authentication in Kafka deployments.

**Comment by jovezhong** [comment]
The current build cannot connect to Confluent Cloud. I guess we need to support SASL_Plain with username/password(ApiKey/SecretKey)

Error message while trying to connect to Confluent Cloud

> /app/pkg/plugins/source.go:109 - rpc error: code = Unknown desc = source server open: failed to create Kafka client: couldn't create consumer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER

**Comment by hariso** [comment]
@jovezhong Thanks for reaching out to us! We plan to implement this in 0.3.0 (which should go out in October). If there's a huge interest in this, we can rethink that. And of course, the community's contribution are more than welcome.: )
