### ISSUE TITLE
More docs around expected error format in connectors, logging, ordering, performance

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#308]
### Feature description

Some common questions we got from developers who wish to write connectors for Conduit:
1. Is there a standard/desired format for errors (since each connector currently does something different)?
2. Is there a standard/desired format for logging (same as above)?
3. Do we need to worry about ordering and/or performance?

Let's clarify these in our documentation, especially the part about errors.

**Comment by lovromazgon** [comment]
These should go into the readme of https://github.com/conduitio/conduit-connector-sdk

**Comment by lovromazgon** [comment]
Resolved in https://github.com/ConduitIO/conduit-connector-sdk/pull/11.
