### ISSUE TITLE
Feature: Compatibility tests for different versions of sources

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#325]
### Feature description

For a number of connectors we support, we usually test a single version of the source (Kafka, Postgres). It would be good if we made it possible to (automatically) test our plugins against different of sources.

**Comment by lovromazgon** [comment]
This issue was split moved and split into the corresponding connector repos:
- https://github.com/ConduitIO/conduit-connector-kafka/issues/16
- https://github.com/ConduitIO/conduit-connector-postgres/issues/20
