### ISSUE TITLE
Plugin management service

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#36]
Create a service for managing plugins. For now this means that we need a list of pre-defined paths to plugins (built-in plugins), these plugins should be loaded up on startup to fetch their specifications and indexed in memory. When a new connector is created the plugin should be fetched by its name from this plugin manager, and not by the path to the plugin as is the case right now. In the future we can add the functionality for adding plugins on the fly, but this is not needed for now.

**Comment by hariso** [comment]
@lovromazgon This appears to be the same as https://github.com/ConduitIO/conduit/issues/427?

**Comment by lovromazgon** [comment]
Indeed!
