### ISSUE TITLE
Extract built-in plugins

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#41]
The conduit repository currently contains built-in plugins. We should rather move them to separate repositories and make sure they are included in Conduit when it's compiled. This way we can easily add more built-in plugins in the future, even ones that are not built and maintained in-house. The easiest way to include them at compile time is to just import them and add them to a global variable containing built-in plugins. The drawback of this approach is that we can only include plugins written in Go (probably not even a problem in the short term).

Depends on #37.

Once a plugin is extracted, we need to adjust the code so it references the extracted [SDK](https://github.com/conduitio/connector-plugin-sdk) instead of Conduit.

- [x] S3 plugin
- [x] Kafka plugin
- [x] Postgres plugin
- [x] File plugin
- [x] Generator plugin

**Comment by neovintage** [comment]
Closing issue! It's done :-)
