### ISSUE TITLE
Connector: Amazon SQS [Source]

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#411]
### Resource name

Amazon SQS

### Resource link

https://aws.amazon.com/sqs/

### Connector type

Source

### Expected connector behavior

This was discussed in a recent team sync-up.

The connector should make it possible to read messages from an Amazon SQS queue. This could make it easier to support Amazon services which already publish notifications about their changes to SQS or it would make it possible to implement some features otherwise impossible to implement (e.g. watch changes in an S3 bucket).

**Comment by lovromazgon** [comment]
Released last month https://github.com/conduitio-labs/conduit-connector-sqs/releases/tag/v0.3.0.
