### ISSUE TITLE
Local directory discovery of connectors

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#427]
On Conduit server, if I have a directory, conduit will be able to see them and use them for pipelines.

**Comment by lovromazgon** [comment]
After this change Conduit will only run plugins it can find in a certain folder. We need to define how plugins can be referred to. Here's my proposal.

`[PLUGIN-TYPE:]PLUGIN-NAME[@VERSION]`

- `PLUGIN-TYPE` (`builtin` or `standalone`)
  - Defines if the specified plugin should be builtin or standalone.
  - The plugin type is optional. If empty, Conduit will use a builtin plugin if it exists and fall back to a standalone plugin.
- `PLUGIN-NAME`
  - Defines the name of the plugin as specified in the plugin specifications, it has to be an exact match.
- `VERSION`
  - Defines the plugin version as specified in the plugin specifications, it has to be an exact match.
  - The version is optional. If empty, Conduit will default to the latest semantic version.

Examples:
- `postgres`
  - will use the **latest** **builtin** **postgres** plugin
  - will fallback to the **latest** **standalone** **postgres** plugin
- `postgres@v0.2.0`
  - will use the **builtin** **postgres** plugin with version **v0.2.0**
  - will fallback to a **standalone** **postgres** plugin with version **v0.2.0**
- `builtin:postgres`
  - will use the **latest** **builtin** **postgres** plugin (no fallback to standalone)
- `standalone:postgres@v0.3.0`
  - will use the **standalone** **postgres** plugin with version **v0.3.0**
