### ISSUE TITLE
connector.yml

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#430]
This should be more of manifest. Not necessarily config that's in code right.

This is related to what lovro is already doing.

**Comment by neovintage** [comment]
This one might be a stretch for 0.3. It's the one that has the least priority.

**Comment by uchennakevinm1** [comment]
This will allow us to discover connectors on github from the community. Low priority for 0.3.0.

**Comment by simonl2002** [comment]
Closing this. No longer relevant.
