### ISSUE TITLE
JavaScript transforms: Provide easy way to work with structured data

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#468]
### Feature description

Currently, it's not possible for JS transforms to return records with changed structured data. This issue has two parts:
1. There's no way in a JS script to create a new structured payload. The helper method Conduit currently provides make it possible to create raw payloads.
2. There's no easy way to modify a structured payload (e.g. replacing a key, adding a new one etc.). The struct used to represent structured data, `record.StructuredData` has the underlying type `map[string]interface{}`, however, due to the explanation given[ here](https://github.com/dop251/goja/issues/399), it's not possible to use it as a map.

**Comment by neovintage** [comment]
We're going to come back to this after we get through OpenCDC and performance benchmarks.
