### ISSUE TITLE
Postgres Source fails when handling bytea primary keys

### ISSUE THREAD

**Issue by dylanlott** [ConduitIO/conduit#47]
# Steps to Reproduce
- Have a Postgres Source configured to read a table that has a primary key column of type `bytea`.
- Configure a pipeline to run that plugin.

# Expected Behavior
The Postgres Source should handle this functionality in the same way it would handle any other key column.

# Actual Behavior
The Postgres connector cannot handle this query correctly and instead of returning the correct result or a descriptive error it returns an `ErrEndData` which implies that the plugin operated correctly and is now at its end.

**Comment by neovintage** [comment]
This should be fixed. @uchennakevinm1 can you link to the appropriate PR / Issue where we did this.

**Comment by uchennakevinm1** [comment]
@neovintage https://github.com/ConduitIO/conduit-connector-postgres/pull/14
