### ISSUE TITLE
Rename Processor.Name to Processor.Type

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#498]
Now that we removed the processor type (transform/filter) we can use the field name "type" for defining which processor needs to be executed (e.g. `hoistfield`, `js`, etc.). This would make for a nicer design, right now the field "name" is also present in the connector and pipeline, although there it serves a different purpose (it's a freeform field, it's mutable and is part of the config). I think the field was named "name" originally because "type" was already taken, and since we now removed that field we can rename "name" to "type".

The pipeline config file will already use this field name so this will consolidate the API with the pipeline config file. This will require a change in the UI though.

Sidenote: remember to update the [processor gauge](https://github.com/ConduitIO/conduit/pull/486#discussion_r907511260).

**Comment by neovintage** [comment]
We'll be ok if we push this off a bit. It's not going to cause any problems with the current features that we're building.
