### ISSUE TITLE
UI: Add file picker when creating a file source

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#53]
DeVaris commented in https://www.notion.so/Conduit-Testing-48d24d2c15b64b4a82e478a39a5d3527?d=cdfdea66aa0d445f801fd2d53849c545#fbbd714f66e94706b3dff24613108c05
> If someone choose a file connector we should present a file picker.

**Comment by simonl2002** [comment]
We will not be doing this in the foreseeable future given the technical limitations going to close.
