### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#566]
### Bug description

Bug 1: destination connector type shows as "source" after stopping pipeline

Bug 2: when pipeline is running, user can't see the connector configurations because of a msg displayed "You must pause the pipeline if you'd like to update it's connectors or transforms." >> user should be able to check the configs while pipeline is running, they only can't change configs
note: the msg has a tiny typo "it's connectors or transforms"> should be "its connectors or transforms"

### Steps to reproduce

First bug:
* Create a file to file pipeline and run it
* stop pipeline
* click the destination connector and try to edit it
* connector type will show as "source"

Second bug:
* Create a file to file pipeline and run it
* click on one of the connectors, you can't edit the connector but you also can't see the configurations, so you won't know what file is the source for example.

### Version

v0.3.0-nightly.20220802-7-g0852b21-dirty darwin/amd64

**Comment by jmar910** [comment]
Bug 1 closed by https://github.com/ConduitIO/conduit/pull/618 (also see related issue https://github.com/ConduitIO/conduit/issues/599)

Bug 2 I think has been closed ? as the configurations are stored in the modal that you can edit here: 
<img width="592" alt="Screen Shot 2022-09-21 at 2 08 23 PM" src="https://user-images.githubusercontent.com/4818826/191579185-2e422e08-13a5-42b1-a711-0d7b25eafd33.png">

I think that maybe its not as prominent as it could be to actually edit a connector from the dropdown on the top right of the right slide panel, so maybe there is something we can do to make that better
