### ISSUE TITLE
Error isn't documented in Swagger

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#581]
The error {"code":9,"message":"failed to delete pipeline: pipeline has connectors attached"} isn’t documented in [Swagger](http://localhost:8080/openapi/#/PipelineService/PipelineService_DeletePipeline)

/v1/pipelines/{id}
Request Method: DELETE
400
message: "failed to delete pipeline: pipeline has connectors attached"

**Comment by lovromazgon** [comment]
Duplicate of https://github.com/ConduitIO/conduit/issues/589.
