### ISSUE TITLE
Bug: Connector which has only destination or source and latest conduit-connector-sdk doesn't work

### ISSUE THREAD

**Issue by maksenius** [ConduitIO/conduit#587]
### Bug description

When I try to create connector which has only source or only destination I get error
`{
    "code": 13,
    "message": "failed to create connector: could not init connector: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.",
    "details": []
}`

Connector has version github.com/conduitio/conduit-connector-sdk v0.2.1-0.20220812170036-f0ac2714fe94
I wait successful creation 

### Steps to reproduce

1. For example lets pull file connector repo (https://github.com/ConduitIO/conduit-connector-file)
2. Set  ` NewSource: nil` in https://github.com/ConduitIO/conduit-connector-file/blob/main/connector.go#L21 . File connector.go will be look like:
```
import sdk "github.com/conduitio/conduit-connector-sdk"

var Connector = sdk.Connector{
	NewSpecification: Specification,
	NewSource:        nil,
	NewDestination:   NewDestination,
}

```
3. Make build.
4. Start Conduit , create pipeline 
```
 curl --location --request POST 'http://localhost:8080/v1/pipelines' \
--header 'Content-Type: application/json' \
--data-raw '{
	"config": {
		"name": "test file",
		"description": "test file pipeline"
	}
}'
```
5. Try create file source 
```


curl --location --request POST 'http://localhost:8080/v1/connectors' \
--header 'Content-Type: application/json' \
--data-raw '{
	"type": "TYPE_DESTINATION",
	"plugin": "YOUR_PATH",
	"pipelineId": "YOUR_PIPELINE_ID",
	"config": {
        "name": "file_destination",
		"settings": {
		"path": "/tmp/test.txt"
		}
	}
}'
```
6. Get error
```
{
    "code": 13,
    "message": "failed to create connector: could not init connector: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.",
    "details": []
}
```

### Version

v0.3.0-nightly.20220823-dirty

**Comment by lovromazgon** [comment]
Thanks @maksenius for a detailed description of the issue! 🙌

**Comment by lovromazgon** [comment]
@maksenius this issue should be fixed in the latest SDK, let us know if you still experience the problem 👍

**Comment by maksenius** [comment]
@lovromazgon Cool
Thank you!
