### ISSUE TITLE
Error code missing in Swagger

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#589]
The error {"code":9,"message":"failed to delete pipeline: pipeline has connectors attached"} isn’t documented in [Swagger](http://localhost:8080/openapi/#/PipelineService/PipelineService_DeletePipeline)

/v1/pipelines/{id}
Request Method: DELETE
400
message: "failed to delete pipeline: pipeline has connectors attached"

**Comment by simonl2002** [comment]
dupe
