### ISSUE TITLE
[Pipelines sreen] The user can't go to the "Pipeline detail" screen

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#592]
[Pipelines sreen] The user can't go to the "Pipeline detail" screen if the "failed to delete pipeline: pipeline has connectors attached" or "failed to delete pipeline: pipeline is running" errors have been handled before

**Comment by uchennakevinm1** [comment]
https://user-images.githubusercontent.com/102546122/186279037-47924a63-d50f-4505-b096-5e4c930c3a47.mp4

**Comment by jmar910** [comment]
@uchennakevinm1 fix is coming here https://github.com/ConduitIO/conduit/pull/641
