### ISSUE TITLE
The user can create the File source/destination connector without the required key "path" in Postman

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#598]
The user can create the File source/destination connector without the required key "path" in Postman
Additional info: the validation of the "path" key is only implemented in the UI
Expected result: the validation of the "path" key is implemented on the backend side
Bug proof:

![Image](https://user-images.githubusercontent.com/102546122/186546987-4ea232a6-fb10-41b6-b330-9154bf675a12.png)

**Comment by jmar910** [comment]
This has been deferred since this is a backend validation issue. This is a non issue from the UI as it displays the appropriate state of a connect (IE no path or path) and lets the user update it to what the UI expects (always having a path).
