### ISSUE TITLE
[The Pipeline detail screen]  400 error is handled when creating the Kafka Destination connector with optional configuration ...

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#600]
[The Pipeline detail screen]  400 error is handled when creating the Kafka Destination connector with optional configuration "acks": "0" or "acks": "1"
Bug is only reproduced when using the UI conduit
 
Additional info: We can create the Kafka Destination connector with optional configuration "acks": "0" or "acks": "1" by using Postman

Logs: 2022-05-06T15:37:53+00:00 ERR error processing HTTP request error="rpc error: code = InvalidArgument desc = proto:\u00a0(line 1:167): invalid value for string type: 0" http_endpoint="POST /v1/connectors" request_id=44de8178-6732-4967-a264-792fc8c4aa71 stack=null
2022-05-06T15:39:10+00:00 ERR error processing HTTP request error="rpc error: code = InvalidArgument desc = proto:\u00a0(line 1:167): invalid value for string type: 1" http_endpoint="POST /v1/connectors" request_id=7f409e72-c3db-41df-a6d6-4d7d5155b06f stack=null

**Comment by jmar910** [comment]
@uchennakevinm1 @hariso I am unable to reproduce this, can we confirm this is still an issue with a proper kafka setup?

**Comment by artemklevtsov** [comment]
Same here with postgres destination. I tried to fill table field.

**Comment by hariso** [comment]
@artemklevtsov Thanks for the details! Which version of Conduit are you running?

**Comment by artemklevtsov** [comment]
> @artemklevtsov Thanks for the details! Which version of Conduit are you running?

Latest stable release: e.g. v0.7.2.

**Comment by lovromazgon** [comment]
UI will be deprecated soon, see https://github.com/ConduitIO/conduit/issues/1911.
