### ISSUE TITLE
Run two identical source connectors with the same config in one pipeline?

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#604]
Is it normal to run two identical source connectors with the same config in one pipeline?
We have two example behavior:
	1	two identical File source connectors - the error isn't occurred and data is transferred
	2	S3 Source connector - the error is occurred (see logs)

Logs:
ERR node stopped error="node 8785f29c-0357-47c4-925d-e9b6accac608 stopped with error: encountered two records with the same position (\"0.0\")" component=pipeline.Service node_id=8785f29c-0357-47c4-925d-e9b6accac608 stack=[{"file":"/Users/serhii/conduit/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":387},{"file":"/Users/serhii/conduit/pkg/pipeline/stream/acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*AckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*AckerNode)).ExpectAck","line":179}]

**Comment by lovromazgon** [comment]
It's a valid thing to run two identical kafka sources both in the same consumer group, for example. So this is a valid use case, we can't restrict it in Conduit, it depends on the connector if such a use is valid or not.

Besides, the error in the logs is already fixed, we don't restrict the position to be unique across records anymore. For that reason I am closing this issue.
