### ISSUE TITLE
Bug: file destination records not readable (base64 encoded)

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#615]
### Bug description

file source to file destination pipeline sends wrong data to destination

example source file:

> one
> two
> three

destination file:

> {"position":"NA==","operation":"create","metadata":{"file.path":"/Users/mahahajja/file1.txt","opencdc.readAt":"1661784344094683000","opencdc.version":"v1"},"key":"MQ==","payload":{"before":null,"after":"b25l"}}
> {"position":"OA==","operation":"create","metadata":{"file.path":"/Users/mahahajja/file1.txt","opencdc.readAt":"1661784344094752000","opencdc.version":"v1"},"key":"Mg==","payload":{"before":null,"after":"dHdv"}}
> {"position":"MTQ=","operation":"create","metadata":{"file.path":"/Users/mahahajja/file1.txt","opencdc.readAt":"1661784344094810000","opencdc.version":"v1"},"key":"Mw==","payload":{"before":null,"after":"dGhyZWU="}}
> 

### Steps to reproduce

1. create a simple file to file pipeline (have some initial data in the source file)
2. run pipeline
3. check destination file

### Version

v0.3.0-nightly.20220809-23-gd6c66d7-dirty darwin/amd64

**Comment by uchennakevinm1** [comment]
related to https://github.com/ConduitIO/conduit/issues/531 (next release)

**Comment by lovromazgon** [comment]
This can now be configured via the output format, see https://github.com/ConduitIO/conduit/issues/831.
