### ISSUE TITLE
Feature: change the pipeline interface to accept the id (not only the pipeline instance)

### ISSUE THREAD

**Issue by maha-hajja** [ConduitIO/conduit#625]
### Feature description

for now, the pipeline interface methods expect the pipeline instance as a parameter (connector and processor services expect the entity id instead).
and this would cause a problem with rolling back an error in pipeline provisioning. https://github.com/ConduitIO/conduit/pull/567#discussion_r958749964

we should either add the option to use (pipeline instance or id), or change all the methods to only accept the pipeline id.

**Comment by neovintage** [comment]
This isn't a showstopper but if we find that the bug is more serious than we had expected, we'll follow up with a patch release to fix this.
