### ISSUE TITLE
Feature: Automate release procedure for connectors

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#632]
### Feature description

As per advice from @neovintage we should create a release for a connector, if it's tied to a specific version of Conduit, which can be due to breaking changes Conduit introduced.

Given the number of connectors have (around 2 dozens), this should be done in an automated way.

**Comment by lovromazgon** [comment]
Builtin connectors:
- https://github.com/ConduitIO/conduit-connector-file/pull/20
- https://github.com/ConduitIO/conduit-connector-generator/pull/24
- https://github.com/ConduitIO/conduit-connector-kafka/pull/49
- https://github.com/ConduitIO/conduit-connector-postgres/pull/63
- https://github.com/ConduitIO/conduit-connector-s3/pull/122

Standalone connectors:
- https://github.com/conduitio-labs/conduit-connector-algolia/pull/3
- https://github.com/conduitio-labs/conduit-connector-azure-storage/pull/23
- https://github.com/conduitio-labs/conduit-connector-bigquery/pull/8
- https://github.com/conduitio-labs/conduit-connector-db2/pull/19
- https://github.com/conduitio-labs/conduit-connector-elasticsearch/pull/27
- https://github.com/conduitio-labs/conduit-connector-firebolt/pull/16
- https://github.com/conduitio-labs/conduit-connector-gcp-pubsub/pull/32
- https://github.com/conduitio-labs/conduit-connector-google-cloudstorage/pull/2
- https://github.com/conduitio-labs/conduit-connector-google-sheets/pull/26
- https://github.com/conduitio-labs/conduit-connector-http-server/pull/1
- https://github.com/conduitio-labs/conduit-connector-marketo/pull/20
- https://github.com/conduitio-labs/conduit-connector-materialize/pull/9
- https://github.com/conduitio-labs/conduit-connector-nats-jetstream/pull/20
- https://github.com/conduitio-labs/conduit-connector-nats-pubsub/pull/11
- https://github.com/conduitio-labs/conduit-connector-oracle/pull/31
- https://github.com/conduitio-labs/conduit-connector-redis/pull/13
- https://github.com/conduitio-labs/conduit-connector-salesforce/pull/25
- https://github.com/conduitio-labs/conduit-connector-snowflake/pull/12
- https://github.com/conduitio-labs/conduit-connector-stripe/pull/5
- https://github.com/conduitio-labs/conduit-connector-vitess/pull/34
- https://github.com/conduitio-labs/conduit-connector-zendesk/pull/9
