### ISSUE TITLE
Make it possible for processor to return multiple records

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#636]
### Feature description

Currently, a processor accepts a single record as an input, and returns a single record as an output.

It would be good if the processor would return multiple records for the following reasons:
* According to @ahmeroxa it's fairly when going to relational databases (e.g. from a denormalized to a normalized data model)
* Some other tools use that too (e.g. Benthos), so doing a switch to Conduit would be easier.

**Comment by ahmeroxa** [comment]
@simonl2002 it's not currently blocking any active projects, so it can wait.

**Comment by lovromazgon** [comment]
Done as part of https://github.com/ConduitIO/conduit/issues/997.
