### ISSUE TITLE
Built-in Config Validation 

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#680]
issues needed to implement builtin config validations:

- [x] #720  
- [x] #694 
- [x] #695 
- [x] #746
- [x] #696

**Comment by lovromazgon** [comment]
Related to parsing and validating configs I see these points:
* Validate constraints before the config reaches the connector or supply utilities to validate them in the connector.
  * This is what the issue mentions - validating and parsing.
  * Figure out if we should do this in Conduit or in the connector SDK. Doing it in Conduit means we could add or fix validations without changing the connector. On the other hand, the connector developer can't do anything if a validation is not doing what they want except removing the validation from the specs. Providing a utility function for validating the config in the SDK would give the developer more flexibility (maybe the only want to automatically validate a part of the config and do the other part manually), also the utility could aid the developer in parsing the config into a struct (we can take ideas from [this](https://pkg.go.dev/encore.dev/config#Load)). Having this in the SDK could potentially make it possible for a developer to specify a custom validation.
* Allow connector developers to specify validations/constraints on parameters (Conduit already kinda supports this but it's not exposed in the SDK).
* Supply a utility function that can be used in `Parameters` to build the parameters map out of a config struct (if it can't be done in runtime we might want to supply a generator).

**Comment by hariso** [comment]
Closing this as all tasks are done.
