### ISSUE TITLE
Move away from buf remote generation

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#762]
Buf is deprecating [remote generation](https://docs.buf.build/reference/deprecated/remote-generation/overview) in favor of [remote plugins](https://docs.buf.build/bsr/remote-plugins/overview) and [remote packages](https://docs.buf.build/bsr/remote-packages/overview). We need to investigate how that affects us and act accordingly (docs contain [migration](https://docs.buf.build/bsr/remote-plugins/migrating-from-alpha) [guides](https://docs.buf.build/bsr/remote-packages/migrating-from-alpha)). Our current remote generation workflow will stop working after April 30, 2023.

**Comment by hariso** [comment]
Closed via #927 and https://github.com/ConduitIO/conduit-connector-protocol/pull/17.
