### ISSUE TITLE
Add More Lifecycle Events for Connectors

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#810]
For some connectors they have actions that need to be taken before they start streaming data or after they're done streaming data. For example, in the Postgres connector you might want to close replication slots on shutdown. given the current methods that can be implemented in connector sdk, this is difficult to do. Proposal is to create at least 2 more lifecycle events;

* At startup 
* At deletion of pipeline

These names aren't set. Please feel free to name them something else.

---

Subtasks:
- [x] #935 
- [x] #936
- [x] #937 
- [x] #938 
- [x] #962

**Comment by uchennakevinm1** [comment]
Need to add to connector protocol and SDK. Need to start with Design.

**Comment by lovromazgon** [comment]
Done! Docs will be added in https://github.com/ConduitIO/conduit/issues/957.
