### ISSUE TITLE
Feature: Force stop pipeline

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#825]
There’s two asks per this:

1. Force Stop - Option to stop  
2. Cascading Delete - for all of the objects attached to a pipeline, you would be able to delete pipeline and all those objects would get deleted too.

**Comment by lovromazgon** [comment]
Done in https://github.com/ConduitIO/conduit/pull/855 and https://github.com/ConduitIO/conduit/pull/856.
