### ISSUE TITLE
Fix broken roadmap automation

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#868]

**Comment by hariso** [comment]
Example of failure: https://github.com/ConduitIO/conduit/actions/runs/4126988861/jobs/7129627575

The error is `gh: Field 'addProjectNextItem' doesn't exist on type 'Mutation'`. `addProjectNextItem` was removed recently (see [changelog](https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2023-01-18)).
