### ISSUE TITLE
Optimize record cloning

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#885]
### Feature description

Record cloning has been implemented (#849) with [copier](https://github.com/jinzhu/copier/), which uses reflection under the hood. This could become a performance bottleneck with high-volume streams.

The reason for this is: the after and before fields in `Record` can be `StructuredData` which is map[string]interface{}. Implementing a deep copy option for `interface{}` would take some time, so for the mentioned PR we chose to first get the functionality fixed (especially because it's easy to reproduce) versus optimizing (for high volume streams).

**Comment by simonl2002** [comment]
We consider this an optimization. No one has encountered this and we will revisit when this has actually becomes a source of pain.
