### ISSUE TITLE
Version not reported in Docker images

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#895]
### Bug description

Version is not reported in Conduit's Docker images.

### Steps to reproduce

1. Run `docker run -p 8080:8080 ghcr.io/conduitio/conduit:v0.5.3`
2. Run `curl -Ss localhost:8080/info | jq .`

**Expected**
Version is reported.

**Actual**
OS and arch. reported, version isn't.
```json
{
  "version": "",
  "os": "linux",
  "arch": "amd64"
}

```

### Version

Docker image ghcr.io/conduitio/conduit:v0.5.3

**Comment by lovromazgon** [comment]
Latest nightly build reports version `v0.7.0-nightly.20230517` 🎉

**Comment by hariso** [comment]
> Latest nightly build reports version `v0.7.0-nightly.20230517` tada

Great news!
