### ISSUE TITLE
Bug: Running Oracle Connector with 0.5.3

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit#903]
### Bug description

In an Oracle-to-file pipeline, no records are read from an Oracle source. This includes snapshot and CDC records. In other words:
1. Rows inserted into the test table before the connector started are not read
2. Rows inserted into the test table after the connector started are not read

 Conduit's logs contain this:
```
2023-02-22T08:22:50+00:00 TRC reading record from source connector component=SourceNode node_id=0eb74781-d30b-4f6d-a1c7-4b5ad03b9dee pipeline_id=cb961224-40cd-4231-98d9-c56f7252dde2
```
After this line, nothing else is logged.

Following is the connector (as fetched from the API):
```json
{
  "id": "0eb74781-d30b-4f6d-a1c7-4b5ad03b9dee",
  "config": {
    "name": "O",
    "settings": {
      "orderingColumn": "ts",
      "table": "TEST_TABLE",
      "url": "oracle://username:password@foobar.amazonaws.com:1521/foobar"
    }
  },
  "type": "TYPE_SOURCE",
  "plugin": "standalone:oracle@ecf836f-dirty",
  "pipelineId": "cb961224-40cd-4231-98d9-c56f7252dde2",
  "processorIds": [],
  "createdAt": "2023-02-22T16:03:52.548122Z",
  "updatedAt": "2023-02-22T16:03:52.548122Z"
}
```

Following is the SQL command used to create the test table:
```sql
CREATE TABLE TEST_TABLE(person_id NUMBER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR2(50) NOT NULL, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(person_id));
```
The tracking table is created and contains the new rows.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/102546122/220797232-e9c1ed1b-b207-4c5b-b6a4-8028bf33f79b.png)

### Version

v0.5.3

**Comment by hariso** [comment]
It turns out that, when new rows were inserted into the test table, no commit was done (and `sqlplus` and SQL Developer which were used didn't have auto-commit set), so no data actually was inserted into the database. With commits the connector works as designed.
