### ISSUE TITLE
document built-in processors

### ISSUE THREAD

**Issue by simonl2002** [ConduitIO/conduit#966]

**Comment by simonl2002** [comment]
processors documentation already exists. likely a dupe of #956

**Comment by simonl2002** [comment]
Reopened, because we incorrectly closed this as a dupe. The goal here is to improve the user-facing docs: https://conduit.io/docs/processors/getting-started/#built-in-processors

**Comment by hariso** [comment]
Pull request: https://github.com/ConduitIO/conduit-site/pull/30.
